version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ~/Projects/linkedingame/namesgames/data:/var/lib/postgresql/data
  rabbitmq3:
    image: rabbitmq:3-management
    container_name: rabbitmq
    user: rabbitmq

    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /

  redis:
    container_name: redis
    image: redis:3.2-alpine
    ports:
      - 6379:6379



