# Generated by Django 3.1.1 on 2020-10-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20201027_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['last_parsed_at']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['company']},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='last_parced_at',
            new_name='last_parsed_at',
        ),
    ]
