# Generated by Django 3.1.1 on 2020-10-29 14:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='slug field', max_length=100, unique=True)),
                ('last_parsed_at', models.DateTimeField(auto_now_add=True, help_text='las-modified')),
            ],
            options={
                'ordering': ['last_parsed_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('picture_url', models.URLField()),
                ('position', models.CharField(max_length=200)),
                ('profile_url', models.URLField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('skype', models.CharField(max_length=50)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_employees', to='company.company')),
            ],
            options={
                'ordering': ['company'],
            },
        ),
    ]
