# Generated by Django 3.1.7 on 2021-02-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='slug field', max_length=100, unique=True, verbose_name='company slug')),
                ('last_parsed_at', models.DateTimeField(auto_now_add=True, help_text='las-modified')),
                ('employees_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['last_parsed_at'],
            },
        ),
    ]
